<?php

declare(strict_types=1);

namespace Modules\User\Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
<<<<<<< HEAD
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;
use Modules\User\Models\Tenant;

=======
use Modules\User\Models\Tenant;

/**
 * @extends Factory<Tenant>
 */
>>>>>>> 6ed19256f (.)
class TenantFactory extends Factory
{
    /**
     * The name of the factory's corresponding model.
     *
<<<<<<< HEAD
     * @var class-string<Model>
=======
     * @var class-string<Tenant>
>>>>>>> 6ed19256f (.)
     */
    protected $model = Tenant::class;

    /**
     * Define the model's default state.
<<<<<<< HEAD
     */
    public function definition(): array
    {
        $name = $this->faker->company();

        return [
            'id' => (string) Str::ulid(),
            'name' => $name,
            'slug' => Str::slug($name).'-'.Str::random(6),
=======
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'id' => $this->faker->uuid(),
            'name' => $this->faker->company(),
            // slug will be auto-generated by HasSlug trait from name
            'domain' => $this->faker->domainName(),
            'database' => $this->faker->word(),
            'is_active' => $this->faker->boolean(),
>>>>>>> 6ed19256f (.)
        ];
    }
}
